---
title: Tertulia NYC
timezone: UTC
collections:
  concerts:
    title: Concerts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: concerts
  values:
    layout: concert
    concert_date: 
    location: 
    group: 
    address: 
    eventbrite_id: 
    thumbnail: 
    feature: 
    food_pic: 
email: your-email@domain.com
description: 'Tertulia is a chamber music series that presents concerts in restaurants,
  in an atmosphere that combines lively conversation and dining with the opportunity
  to hear some of the greatest performers of our time.

'
baseurl: 
url: http://yourdomain.com
twitter_username: 
github_username: Tertulia
markdown: kramdown
